language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modeules
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master